# Generated by Django 6.0.5 on 2026-05-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name:')),
                ('description', models.TextField(verbose_name='descriptions:')),
                ('launch_date', models.DateField(verbose_name='date')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Record date')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='rocord date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255, verbose_name='text')),
                ('votes', models.IntegerField(default=0, verbose_name='vote number')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.survey', verbose_name='poll')),
            ],
        ),
    ]
