# Generated by Django 6.0.5 on 2026-05-25 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vote_unique_together_vote_uniqu_user_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='uniqu_user_choice',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'choice'), name='unique_user_choice'),
        ),
    ]
