# Generated by Django 6.0.5 on 2026-06-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
